FROM nginx:1.19.2-alpine

LABEL author="Ercy Moreira Neto <fireball.vb@gmail.com>"

# COPY nginx.conf /etc/nginx/

# RUN echo "upstream php-upstream { server php-fpm:9000; }" > /etc/nginx/conf.d/upstream.conf


RUN apk add bash